Change Ollama AddModel to create a separate resource
CommunityToolkit/Aspire pull request #143
Opened 2024-10-23 22:12 UTC by Mrxx99

**Closes #119 <ISSUE_NUMBER>**

As discussed in #119 this changes the AddModel methods on Ollama resource to create and return a new OllamaModelResosurce, that can be used with WithReference instead of using the Ollama resource.
The advantage is, that now one Ollama resource can have multiple models, that are referenced by same or different applications. Previously only the default model could be used without manually setting complicated env variables.

## PR Checklist

- [x] Created a feature/dev branch in your fork (vs. submitting directly from a commit on main)
- [x] Based off latest main branch of toolkit
- [x] PR doesn't include merge commits (always rebase on top of our main, if needed)
- [ ] New integration
  - [ ] Docs are written
  - [ ] Added description of major feature to project description for NuGet package (4000 total character limit, so don't push entire description over that)
- [ ] Tests for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Contains **NO** breaking changes
- [ ] Every new API (including internal ones) has full XML docs
- [ ] Code follows all style conventions

This is a breaking change so I guess v9 would be a good target for this.
It breaks how AddModel works previously it would return the Ollama resource back, so whenever this was used, the code would have to change to call AddModel on a variable that was returned from AddOllama instead. The WithDefaultValue still works, this limits a bit the breaking change.

## Other information

This is still work in progress, but I already created the PR, so some design decisions can be discussed.
E.g. should it still work with a custom WithReference extension and environment variables or could a connection string that includes the model name be used instead? The PR implementation provides both but uses the custom WithReference one, if that method was removed it would use the connection string one.

2024-10-24 00:12 UTC, aaronpowell reviewed
This looks **amazing**, thanks @Mrxx99!

I have one question about the connection string for models and I think doing it would help address #107

2024-10-24 00:12 UTC, aaronpowell commented on src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaModelResource.cs
> +    public ReferenceExpression ConnectionStringExpression => ReferenceExpression.Create($"{Parent}?Model={ModelName}");
This is getting me to rethink the "connection string" concept that we have and whether we should go to a "real" connection string like `Endpoint=...;Model=...` structure.

That would be a breaking change but it does align better with how other Aspire integrations work (and we can use the `DbConnectionStringBuilder` class to parse it).

2024-10-24 00:25 UTC, aaronpowell commented
Let's also change this to merge into the aspire-9 branch not main

2024-10-26 19:40 UTC, Mrxx99 commented
@aaronpowell  I did the change to use a proper DB connection string and removed the environments variables. Should the 'WithDefaultModel' approach be kept or also removed?

2024-10-27 22:40 UTC, aaronpowell commented
Let's use the connection string approach the whole way down. We can accept a breaking change going into the v9 release (which this will land) as we're also really only soft launched at the moment so usage is low (and thus if we were to change things "radically" it won't be a huge problem).

Same goes for the `WithDefaultModel`, let's remove that as there's now a better approach to providing that through the work you've done.

2024-10-27 22:48 UTC, aaronpowell requested changes
Got a few more changes in here but it's shaping up really nicely.

I'm loving how the integration now looks

2024-10-27 22:48 UTC, aaronpowell commented on examples/ollama/CommunityToolkit.Aspire.Hosting.Ollama.AppHost/Program.cs
> +    .WithDefaultModel("phi:chat")
As mentioned in a recent comment, let's remove the `WithDefaultModel` method and instead you always use `WithModel` and provide the model reference.

2024-10-27 22:48 UTC, aaronpowell commented on src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaResource.cs
> +        }
We'll be able to drop this with the removal of the concept of default model

2024-10-27 22:48 UTC, aaronpowell commented on src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaResourceBuilderExtensions.cs
> +    public static IResourceBuilder<OllamaModelResource> AddHuggingFaceModel(this IResourceBuilder<OllamaResource> builder, string name, string modelName)
This method could do a pass-through to the `AddModel` with the prefix of `hf.co/`, which would reduce a little bit of code duplication.

2024-10-27 22:48 UTC, aaronpowell commented on src/CommunityToolkit.Aspire.Hosting.Ollama/OllamaResourceBuilderExtensions.cs
> +        return builder;
As discussed, let's remove this method and instead you'll use the `OllamaModelResource` as the thing you pass in if you want a default model specified.

2024-10-27 22:48 UTC, aaronpowell commented on src/CommunityToolkit.Aspire.Hosting.Ollama/PublicAPI.Shipped.txt
> -static Aspire.Hosting.OllamaResourceBuilderExtensions.AddModel(this Aspire.Hosting.ApplicationModel.IResourceBuilder<Aspire.Hosting.ApplicationModel.OllamaResource!>! builder, string! modelName) -> A
We need to leave this method here and instead it'll get marked with REMOVED in the unshipped file.

@Alirexaa we should document this in the contributing guide better.

2024-10-27 22:48 UTC, aaronpowell commented on src/CommunityToolkit.Aspire.Hosting.Ollama/PublicAPI.Shipped.txt
> -static Aspire.Hosting.OllamaResourceBuilderExtensions.WithReference<T>(this Aspire.Hosting.ApplicationModel.IResourceBuilder<T>! builder, Aspire.Hosting.ApplicationModel.IResourceBuilder<Aspire.Hosti
We need to leave this method here and instead it'll get marked with REMOVED in the unshipped file.

2024-10-27 22:48 UTC, aaronpowell commented on src/CommunityToolkit.Aspire.OllamaSharp/AspireOllamaSharpExtensions.cs
> +    private const string DefaultConfigSectionName = "Aspire:Ollama";
This needs to stick with `OllamaSharp` as that's the client this is relevant for

2024-10-28 21:57 UTC, mitchdenny commented
This PR is kind of setting a convention for how to pass around the model name in the connection string. I think this is probably the right thing to do but I know that this has been a contentious issue so should be discussed.

For me the most important thing is the understand how a developer moves between different API providers. So for local development they are probably going to use Ollama, but when they deploy do they want to adopt Open AI/Azure Open AI. Can they host things

```csharp
var builder = DistributedApplication.CreateBuilder(args);
IResourceBuilder<IResourceWithConnectionString> model = builder.ExecutionContext.IsRunMode
                                                          ? builder.AddOllama(...).AddModel(...)
                                                          : builder.AddAzureOpenAI(...).AddModel(...);
```

2024-10-30 00:11 UTC, aaronpowell approved these changes
I feel like this is ready to go

2024-10-30 00:13 UTC, aaronpowell commented
> This PR is kind of setting a convention for how to pass around the model name in the connection string. I think this is probably the right thing to do but I know that this has been a contentious issue so should be discussed.
> 
> For me the most important thing is the understand how a developer moves between different API providers. So for local development they are probably going to use Ollama, but when they deploy do they want to adopt Open AI/Azure Open AI. Can they host things
> 
> ```cs
> var builder = DistributedApplication.CreateBuilder(args);
> IResourceBuilder<IResourceWithConnectionString> model = builder.ExecutionContext.IsRunMode
>                                                           ? builder.AddOllama(...).AddModel(...)
>                                                           : builder.AddAzureOpenAI(...).AddModel(...);
> ```

There are some complexities that come with transitioning between different AI services, but I think that the introduction of the Microsoft.Extensions.AI (and the updates coming in #164 to support it for Ollama) will help with that by having the client abstraction away and then it becomes a case of the client integration <-> hosting integration, as you'd likely use OllamaSharp + Ollama Hosting then move to the OpenAI/Azure OpenAI set.

2024-10-31 04:10 UTC, aaronpowell commented
@Mrxx99 - I think we're looking good, anything left from your end before putting this in for a merge?

2024-10-31 07:56 UTC, aaronpowell commented
> Should we keep the AddModel(string) overload where the resource name is generated? I am not 100% sure about the sanitizing.

I think we can combine them into a single method, make `modelName` optional and if it's not provided we use `name` for it.

Digging through Aspire's source, I can't see anywhere that would have a problem if the resource name as non-alphanumeric characters, so we could probably get away with a resource named `phi3:chat` or `huggingface.io/something`.

2024-11-01 03:44 UTC, merged

2024-11-01 03:52 UTC, aaronpowell commented
I've decided to merge it as-is so I can get a head start on the merge conflicts that will come with #164 

Thanks again, I'm really excited at how the Ollama integration is now looking.