codeowners update
CommunityToolkit/Aspire pull request #315
Opened 2024-12-06 08:29 UTC by MichielBrys

**Closes #<ISSUE_NUMBER>**

## PR Checklist

- [ ] Created a feature/dev branch in your fork (vs. submitting directly from a commit on main)
- [ ] Based off latest main branch of toolkit
- [ ] PR doesn't include merge commits (always rebase on top of our main, if needed)
- [ ] New integration
  - [ ] Docs are written
  - [ ] Added description of major feature to project description for NuGet package (4000 total character limit, so don't push entire description over that)
- [ ] Tests for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Contains **NO** breaking changes
- [ ] Every new API (including internal ones) has full XML docs
- [ ] Code follows all style conventions

## Other information

2024-12-07 02:42 UTC, aaronpowell approved these changes

2024-12-07 23:39 UTC, aaronpowell commented
@michielb I've invited you to the contributor team which will resolve the error on the CODEOWNERS file

2024-12-08 07:23 UTC, aaronpowell requested changes

2024-12-08 07:23 UTC, aaronpowell commented on CODEOWNERS
> +
```suggestion
/examples/masstransit-rabbitmq/ @michielb
/src/CommunityToolkit.Aspire.MassTransit.RabbitMQ/ @michielb
/tests/CommunityToolkit.Aspire.MassTransit.RabbitMQ.Tests/ @michielb

```

2024-12-08 07:23 UTC, aaronpowell approved these changes

2024-12-08 07:25 UTC, aaronpowell commented
Bummer, I can't fix the merge issue on mobile

2024-12-08 07:45 UTC, Alirexaa commented
> Bummer, I can't fix the merge issue on mobile

I will do.

2024-12-08 21:02 UTC, MichielBrys commented
Oh I made a mistake, its supposed to be @MichielBrys

2024-12-09 00:06 UTC, aaronpowell commented on CODEOWNERS
> +/tests/CommunityToolkit.Aspire.MassTransit.RabbitMQ.Tests/ @michielb
```suggestion
/examples/masstransit-rabbitmq/ @MichielBrys
/src/CommunityToolkit.Aspire.MassTransit.RabbitMQ/ @MichielBrys
/tests/CommunityToolkit.Aspire.MassTransit.RabbitMQ.Tests/ @MichielBrys
```

2024-12-09 00:06 UTC, aaronpowell commented
> Oh I made a mistake, its supposed to be @MichielBrys

I've proposed a suggested change, is that right?

2024-12-10 05:34 UTC, aaronpowell requested changes
Verify the right owner is set

2024-12-10 12:38 UTC, MichielBrys commented
Yes thats correct, sorry for the delay. Thanks :)

2024-12-11 23:43 UTC, aaronpowell approved these changes

2024-12-11 23:45 UTC, aaronpowell commented
> Yes thats correct, sorry for the delay. Thanks :)

Make sure you accept the invite that was sent then it's good to merge (otherwise the file is marked as invalid since you're not a member)

2024-12-16 14:08 UTC, MichielBrys commented
Thanks for the invite Aaron, I wasn't available the last few days and it seems the invitation has been revoked or expired. Could you please send another one? I'll accept that one first thing tomorrow. My apologies :)

2024-12-18 03:34 UTC, aaronpowell commented
> Thanks for the invite Aaron, I wasn't available the last few days and it seems the invitation has been revoked or expired. Could you please send another one? I'll accept that one first thing tomorrow. My apologies :)

done

2024-12-18 14:37 UTC, MichielBrys commented
invite accepted

2024-12-18 23:34 UTC, merged